######################################################################
#  Project
######################################################################

BINARY		= myblink
SRCFILES	= myblink.c

all: elf bin

include ../Makefile.incl

# End
